INSERT INTO EMP_CIDADE (CIDADE_NOME) VALUES ('São Paulo');
INSERT INTO EMP_CIDADE (CIDADE_NOME) VALUES ('Rio de Janeiro');

INSERT INTO EMP_USUARIO (
    USUARIO_NOME, USUARIO_LOGIN, USUARIO_SENHA, USUARIO_DESCRICAO, 
    USUARIO_FOTO, USUARIO_CONTATO, USUARIO_ENDERECO, USUARIO_CIDADE
) VALUES (
    'João Silva', 'joaos', 'senha123', 'Desenvolvedor full-stack',
    'foto1.jpg', 'joao@email.com', 'Rua A, 123', 1
);

INSERT INTO EMP_USUARIO (
    USUARIO_NOME, USUARIO_LOGIN, USUARIO_SENHA, USUARIO_DESCRICAO, 
    USUARIO_FOTO, USUARIO_CONTATO, USUARIO_ENDERECO, USUARIO_CIDADE
) VALUES (
    'Tech Solutions', 'techsol', 'empresa123', 'Empresa de tecnologia',
    'logo.jpg', 'contato@techsol.com', 'Av. Central, 500', 2
);

INSERT INTO EMP_CATEGORIA_HABILIDADE (CATEGORIA_NOME) VALUES ('Desenvolvimento');
INSERT INTO EMP_CATEGORIA_HABILIDADE (CATEGORIA_NOME) VALUES ('Design');

INSERT INTO EMP_HABILIDADE (HABILIDADE_NOME, HABILIDADE_CATEGORIA) VALUES ('JavaScript', 1);
INSERT INTO EMP_HABILIDADE (HABILIDADE_NOME, HABILIDADE_CATEGORIA) VALUES ('UI/UX', 2);

INSERT INTO EMP_PROFISSIONAL (
    PROFISSIONAL_USUARIO_ID, PROFISSIONAL_EMPREGADO, PROFISSIONAL_ANOS_DE_SERV, PROFISSIONAL_AVALIACOES
) VALUES (
    1, 'S', 5, 10
);

INSERT INTO EMP_EMPRESA (
    USUARIO_EMPRESA_ID, EMPRESA_WEBSITE, EMPRESA_NOTA_MEDIA
) VALUES (
    2, 'https://www.techsol.com', 4.5
);

INSERT INTO EMP_PROFISSIONAL_HABILIDADE (PROFISSIONAL_USUARIO_ID, HABILIDADE_ID) VALUES (1, 1);
INSERT INTO EMP_PROFISSIONAL_HABILIDADE (PROFISSIONAL_USUARIO_ID, HABILIDADE_ID) VALUES (1, 2);

INSERT INTO EMP_VAGA (
    VAGA_TITULO, VAGA_DESCRICAO, VAGA_SALARIO, VAGA_EMPRESA,
    VAGA_REMOTO, VAGA_PRESENCIAL, VAGA_PERIODO, VAGA_OCUPADA, VAGA_NOTA_MEDIA
) VALUES (
    'Desenvolvedor Front-End', 'Trabalhe com React e TypeScript.', 8000.00, 2,
    'S', 'N', 'Integral', 'N', 4.2
);

INSERT INTO EMP_VAGA_HABILIDADE (VAGA_ID, HABILIDADE_ID) VALUES (1, 1);
INSERT INTO EMP_VAGA_HABILIDADE (VAGA_ID, HABILIDADE_ID) VALUES (1, 2);

INSERT INTO EMP_AVALIACAO (
    AVALIACAO_DESCRICAO, AVALIACAO_NOTA, AVALIACAO_VAGA, AVALIACAO_EMPRESA
) VALUES (
    'Excelente oportunidade, processo seletivo rápido.', 4.8, 1, 2
);